version: "3.7"

services:
  nginx:
    build:
      context: docker/nginx
    ports:
      - "8080:80"
#      - "8443:443"
    volumes:
      - ./:/var/www
    depends_on:
      - php-fpm
  php-fpm:
    build:
      args:
        USER_ID: 1000
        GROUP_ID: 1000
      context: docker/php-fpm
    volumes:
      - ./:/var/www
    environment:
      XDEBUG_CONFIG: "remote_host=172.17.0.1  remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    ports:
      - 8084:80
    environment:
      - PMA_HOST=${DB_CONNECTION}
      - PMA_USER=${DB_USERNAME}
      - PMA_PASSWORD=${DB_PASSWORD}
volumes:
  db:
    driver: local
